import { Content } from "./content-interface";

export const contents: Content[] = [
    {
      id: 0,
      title: "Porsche",
      description: "high speed sports car generated by british motors.",
      creator: "porsche",
      imgURL: "/assets/images/car1.jfif",
      type: "Super Sport",
      tags: ["Kawasaki", "Ninja", "Super Sport"]
    },
    {
      id: 1,
      title: "ferrari",
      description: ";lcMKAMSCIJEFQE ECIERERIVGIQJGVcmsecoiciewrrer9gfr wefewrhfer8gfn suicewhf8hervherifh",
      creator: "zc kcsdnrnvuarvr",
      imgURL: "/assets/images/car1.jfif",
      type: "Super Sport",
      tags: ["Yamaha", "R1", "Super Sport"]
    },
    {
      id: 2,
      title: "Toyota",
      description: "as;lcmsdmjoierj sdcdisdijoiajer sndcaier",
      creator: "toyota",
      imgURL: "/assets/images/car2.jfif",
      tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
    },
    {
        id: 3,
        title: "suzuki",
        description: "asl;clksdmckemoier swcerkmaerverjvger",
        creator: "szukzi",
        imgURL: "/assets/images/car4.jfif",
        tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
      },
    
      {
        id: 4,
        title: "mercs",
        description: "cl;dsamcsmierf seccmoirfierjroe.",
        creator: "mercs",
        imgURL: "/assets/images/car2.jfif",
        tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
      },
    
      {
        id: 5,
        title: "ford",
        description: "ccjksdncjsnvaeunvei sdjc jsdncsnverviu.",
        creator: "ford",
        imgURL: "/assets/images/car1.jfif",
        tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
      },
    
      {
        id: 6,
        title: "mustang",
        description: "mustang is a supercharged supersport-class car in the Ninja sports bike series manufactured by Kawasaki, featuring a variable-speed centrifugal supercharger.",
        creator: "mustang",
        imgURL: "/assets/images/car4.jfif",
        tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
      },
      
      {
        id: 7,
        title: "dodge",
        description: "aasdclkscnoiernoeinjoi ,asc welkfh304f erm,  eroicvnqergjqehg",
        creator: "dodge",
        imgURL: "/assets/images/car3.jfif",
        tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
      },
      
    
      {
        id: 8,
        title: "challenger",
        description: "acnjksnernvquigh wencoiwcnierherhgem nwifnerignqerugheq",
        creator: "dodge",
        imgURL: "/assets/images/car2.jfif",
        tags: ["Kawasaki", "NinjaH2", "Hyper Sport"]
      },
      
  ]